# Generated by Django 3.1.2 on 2020-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201112_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('price', models.IntegerField(max_length=10)),
                ('reference', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
